# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main", "v0.1" ]
  pull_request:
    branches: [ "main", "v0.1" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# matrix setup for multiple versions and OSs
# License: MIT

jobs:
  raku:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macOS-latest
          - windows-latest
        raku-version:
          - "latest"
          - "2022.03"
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: Raku/setup-raku@v1
        with:
          raku-version: ${{ matrix.raku-version }}
      - run: raku -v # <= use or delete this
      - run: zef install . --deps-only --test-depends --/test
      - run: zef install --/test App::Prove6
      - run: prove6 -I. --verbose

      # add commands below for your own requirements

